# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 15:09
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=60)),
                ('avatar', models.ImageField(default='default.jpg', upload_to=account.models.upload_avatar)),
                ('age', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(default='', max_length=70)),
                ('bio', models.CharField(default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
