# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_image),
        ),
    ]
