# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authour',
            new_name='author',
        ),
    ]
